var user = [{
  "login": "gt7348b",
  "id": 8863455,
  "avatar_url": "https://avatars.githubusercontent.com/u/8863455?v=2",
  "gravatar_id": "",
  "url": "https://api.github.com/users/gt7348b",
  "html_url": "https://github.com/gt7348b",
  "followers_url": "https://api.github.com/users/gt7348b/followers",
  "following_url": "https://api.github.com/users/gt7348b/following{/other_user}",
  "gists_url": "https://api.github.com/users/gt7348b/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/gt7348b/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/gt7348b/subscriptions",
  "organizations_url": "https://api.github.com/users/gt7348b/orgs",
  "repos_url": "https://api.github.com/users/gt7348b/repos",
  "events_url": "https://api.github.com/users/gt7348b/events{/privacy}",
  "received_events_url": "https://api.github.com/users/gt7348b/received_events",
  "type": "User",
  "site_admin": false,
  "name": "John Crocker",
  "company": "",
  "blog": "",
  "location": "Atlanta, GA",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 10,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-09-22T16:03:59Z",
  "updated_at": "2014-10-08T16:22:11Z"
}
]
